services:
  - type: web
    name: matchmaking-backend
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 5000
      - key: MONGODB_URI
        sync: false # This means you'll set this manually in the Render dashboard
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        sync: false # Set this manually for security